# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/hashicorp/go-getter
%global goipath         github.com/hashicorp/go-getter
Version:                1.6.2

%gometa

%global goname go-getter

%global common_description %{expand:
Package for downloading things from a string URL using a variety of protocols.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Package for downloading things from a string URL using a variety of protocols

# Upstream license specification: MPL-2.0
License:        MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
# Remove tests that require Internet connection
rm get_gcs_test.go get_git_test.go get_http_test.go get_s3_test.go

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/cmd/%{name} %{goipath}/cmd/%{name}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/cmd/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
