# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/inconshreveable/go-update
%global goipath         github.com/inconshreveable/go-update
%global commit          8152e7eb6ccf8679a64582a66b78519688d156ad

%gometa

%global common_description %{expand:
Build self-updating Golang programs.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Build self-updating Golang programs

# Upstream license specification: BSD-3-Clause and Apache-2.0
License:        BSD and ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

# for check
BuildRequires: bsdiff

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1.20210817git8152e7e
- Initial package

