# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/GoogleCloudPlatform/docker-credential-gcr
%global goipath         github.com/GoogleCloudPlatform/docker-credential-gcr
Version:                2.0.5

%gometa

%global common_description %{expand:
A Docker credential helper for GCR users.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Docker credential helper for GCR users

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/docker/cli/cli/config)
BuildRequires:  golang(github.com/docker/cli/cli/config/configfile)
BuildRequires:  golang(github.com/docker/docker-credential-helpers/credentials)
BuildRequires:  golang(github.com/golang/mock/gomock)
BuildRequires:  golang(github.com/google/subcommands)
BuildRequires:  golang(github.com/toqueteos/webbrowser)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(golang.org/x/oauth2/google)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/docker-credential-gcr %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
# ignore e2e tests as they require GCR credentials
%gocheck -r test
%endif

%files
%license LICENSE
%doc CONTRIBUTING.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 2.0.5-1%{?dist}
- Initial package

