# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/bmatcuk/doublestar
%global goipath         github.com/bmatcuk/doublestar
Version:                1.3.4

%gometa

%global common_description %{expand:
Implements support for double star (**) matches in golang's path.Match and
filepath.Glob.}

%global golicenses      LICENSE
%global godocs          examples README.md UPGRADING.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Implements support for double star (**) matches in golang's path.Match and filepath.Glob

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
# skip one failing test
Patch0001:      0001-Skip-test-from-old-release-that-currently-fail.patch

%description
%{common_description}

%gopkg

%prep
%goprep
%patch0001 -p1

%install
%gopkginstall

# skip TestMatch with patch0001
%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.3.4-1
- Initial package

