# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/liamg/clinch
%global goipath         github.com/liamg/clinch
Version:                1.5.6

%gometa

%global common_description %{expand:
Go CLI toolkit :hammer:.}

%global golicenses      LICENSE
%global godocs          _examples README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go CLI toolkit :hammer:

License:        Unlicense
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/liamg/tml)
BuildRequires:  golang(github.com/pkg/term)
BuildRequires:  golang(golang.org/x/crypto/ssh/terminal)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.5.6-1%{?dist}
- Initial package

