# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/owenrumney/squealer
%global goipath         github.com/owenrumney/squealer
Version:                0.2.28

%gometa

%global common_description %{expand:
Scans a local git repository for secrets that are being leaked deep within the
commit history}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Scans a local git repository for secrets that are being leaked deep within the commit history

License:        Unlicense
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-git/go-git/v5)
BuildRequires:  golang(github.com/go-git/go-git/v5/plumbing)
BuildRequires:  golang(github.com/go-git/go-git/v5/plumbing/object)
BuildRequires:  golang(github.com/owenrumney/go-sarif/sarif)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.2.28-1
- Initial package

