# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/gitleaks/go-gitdiff
%global goipath         github.com/gitleaks/go-gitdiff
Version:                0.7.6

%gometa

%global common_description %{expand:
Go library for parsing and applying patches created by Git.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go library for parsing and applying patches created by Git

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# gitleak's fork has some changes that break tests
# notified developer as project doesn't accept issues
#%%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
