# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/owenrumney/go-sarif
%global goipath         github.com/owenrumney/go-sarif
Version:                1.0.11

%gometa

%global common_description %{expand:
Go library for sarif - Static Analysis Results Interchange Format.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library for sarif - Static Analysis Results Interchange Format

License:        Unlicense
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/zclconf/go-cty/cty)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.0.11-1%{?dist}
- Initial package

