# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/toqueteos/webbrowser
%global goipath         github.com/toqueteos/webbrowser
Version:                1.2.0

%gometa

%global common_description %{expand:
:globe_with_meridians::snake: Python's webbrowser in Go. Simple API for opening
web pages on your default browser.}

%global golicenses      LICENSE.md
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        :globe_with_meridians::snake: Python's webbrowser in Go. Simple API for opening web pages on your default browser

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.2.0-1%{?dist}
- Initial package

