# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/foxcpp/go-mockdns
%global goipath         github.com/foxcpp/go-mockdns
Version:                1.0.0

%gometa

%global common_description %{expand:
Boilerplate for testing of code involving DNS lookups, including unholy hacks
to redirect net.Lookup* calls.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Boilerplate for testing of code involving DNS lookups, including unholy hacks to redirect net.Lookup* calls

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
