# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/owenrumney/go-sarif
%global goipath         github.com/owenrumney/go-sarif
Version:                2.1.2

%gometa

%global common_description %{expand:
Go library for sarif - Static Analysis Results Interchange Format.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go library for sarif - Static Analysis Results Interchange Format

License:        Unlicense
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
