# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/golang-jwt/jwt
%global goipath         github.com/golang-jwt/jwt/v4
Version:                4.0.0

%gometa

%global common_description %{expand:
Community maintained clone of https://github.com/dgrijalva/jwt-go.}

%global golicenses      LICENSE
%global godocs          MIGRATION_GUIDE.md VERSION_HISTORY.md README.md\\\
                        cmd/jwt/README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Community maintained clone of https://github.com/dgrijalva/jwt-go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc MIGRATION_GUIDE.md VERSION_HISTORY.md README.md cmd/jwt/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 4.0.0-1%{?dist}
- Initial package

