# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/oras-project/oras-go
%global goipath         oras.land/oras-go
%global forgeurl        https://github.com/oras-project/oras-go
Version:                1.2.0

%gometa

%global common_description %{expand:
ORAS Go library.}

%global golicenses      LICENSE
%global godocs          examples CODE_OF_CONDUCT.md OWNERS.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        ORAS Go library

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
