# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/spf13/cobra
%global goipath         github.com/spf13/cobra
Version:                1.2.1

%gometa

%global common_description %{expand:
A Commander for modern Go CLI interactions.}

%global golicenses      LICENSE.txt cobra/cmd/license_lgpl.go\\\
                        cobra/cmd/license_gpl_3.go cobra/cmd/license_gpl_2.go\\\
                        cobra/cmd/licenses.go\\\
                        cobra/cmd/license_bsd_clause_2.go\\\
                        cobra/cmd/license_mit.go cobra/cmd/license_agpl.go\\\
                        cobra/cmd/license_apache_2.go\\\
                        cobra/cmd/license_bsd_clause_3.go
%global godocs          doc powershell_completions.md bash_completions.md\\\
                        CONTRIBUTING.md CHANGELOG.md shell_completions.md\\\
                        projects_using_cobra.md fish_completions.md\\\
                        user_guide.md CONDUCT.md README.md zsh_completions.md\\\
                        cobra/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A Commander for modern Go CLI interactions

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/cpuguy83/go-md2man/v2/md2man)
BuildRequires:  golang(github.com/spf13/pflag)
BuildRequires:  golang(github.com/spf13/viper)
BuildRequires:  golang(gopkg.in/yaml.v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cobra cobra/tpl; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt cobra/cmd/license_lgpl.go cobra/cmd/license_gpl_3.go
%license cobra/cmd/license_gpl_2.go cobra/cmd/licenses.go
%license cobra/cmd/license_bsd_clause_2.go cobra/cmd/license_mit.go
%license cobra/cmd/license_agpl.go cobra/cmd/license_apache_2.go
%license cobra/cmd/license_bsd_clause_3.go
%doc doc powershell_completions.md bash_completions.md CONTRIBUTING.md
%doc CHANGELOG.md shell_completions.md projects_using_cobra.md
%doc fish_completions.md user_guide.md CONDUCT.md README.md zsh_completions.md
%doc cobra/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.2.1-1%{?dist}
- Initial package

