# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/vektah/gqlparser
%global goipath         github.com/vektah/gqlparser/v2
Version:                2.4.6

%gometa

%global common_description %{expand:
A port of the parser from graphql-js into golang.}

%global golicenses      LICENSE validator/imported/LICENSE
%global godocs          readme.md validator/imported/readme.md

Name:           %{goname}
Release:        %autorelease
Summary:        A port of the parser from graphql-js into golang

# Upstream license specification: MIT and BSD-3-Clause
License:        MIT and BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
