# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/zclconf/go-cty-yaml
%global goipath         github.com/zclconf/go-cty-yaml
Version:                1.0.2

%gometa

%global common_description %{expand:
YAML marshalling and unmarshalling for go-cty}

%global golicenses      LICENSE.libyaml NOTICE LICENSE
%global godocs          CHANGELOG.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        YAML marshalling and unmarshalling for go-cty

# Upstream license specification: MIT and Apache-2.0
License:        MIT and ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/zclconf/go-cty/cty)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/convert)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/function)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.0.2-1
- Initial package

