# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/bmatcuk/doublestar
%global goipath         github.com/bmatcuk/doublestar
Version:                4.0.2

%gometa

%global common_description %{expand:
Implements support for double star (**) matches in golang's path.Match and
filepath.Glob.}

%global golicenses      LICENSE
%global godocs          examples README.md UPGRADING.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Implements support for double star (**) matches in golang's path.Match and filepath.Glob

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 4.0.2-1%{?dist}
- Initial package

