# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/go-git/go-billy
%global goipath         github.com/go-git/go-billy/v5
Version:                5.3.1

%gometa

%global common_description %{expand:
The missing interface filesystem abstraction for Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        The missing interface filesystem abstraction for Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)
BuildRequires:  golang(gopkg.in/check.v1)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 5.3.1-1%{?dist}
- Initial package

