# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/aquasecurity/testdocker
%global goipath         github.com/aquasecurity/testdocker
%global commit          097d418f8cdbc3694fac32d23f06c7934e07cdf7

%gometa

%global common_description %{expand:
Test utilities for Docker Engine/Registry.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Test utilities for Docker Engine/Registry

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/docker/docker/api/server/httputils)
BuildRequires:  golang(github.com/docker/docker/api/server/router)
BuildRequires:  golang(github.com/docker/docker/api/types)
BuildRequires:  golang(github.com/docker/docker/api/types/container)
BuildRequires:  golang(github.com/docker/docker/api/types/image)
BuildRequires:  golang(github.com/docker/docker/errdefs)
BuildRequires:  golang(github.com/docker/docker/pkg/ioutils)
BuildRequires:  golang(github.com/docker/go-connections/nat)
BuildRequires:  golang(github.com/golang-jwt/jwt/v4)
BuildRequires:  golang(github.com/google/go-containerregistry/pkg/v1)
BuildRequires:  golang(github.com/google/go-containerregistry/pkg/v1/tarball)
BuildRequires:  golang(github.com/gorilla/mux)
BuildRequires:  golang(golang.org/x/xerrors)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0-0.1%{?dist}.20210817git097d418
- Initial package

