# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/go-git/go-git-fixtures
%global goipath         github.com/go-git/go-git-fixtures/v4
Version:                4.2.2

%gometa

%global common_description %{expand:
Several git fixtures to run go-git tests.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Several git fixtures to run go-git tests

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-git/go-billy/v5)
BuildRequires:  golang(github.com/go-git/go-billy/v5/osfs)
BuildRequires:  golang(github.com/go-git/go-billy/v5/util)
BuildRequires:  golang(gopkg.in/check.v1)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck -r tgz
%endif

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 4.2.2-1%{?dist}
- Initial package

