# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/agnivade/levenshtein
%global goipath         github.com/agnivade/levenshtein
Version:                1.1.1

%gometa

%global common_description %{expand:
Go implementation to calculate Levenshtein Distance.}

%global godocs          License.txt README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go implementation to calculate Levenshtein Distance

License:        MIT

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
