# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/owenrumney/squealer
%global goipath         github.com/owenrumney/squealer
Version:                1.1.0

%gometa

%global goname squealer

%global common_description %{expand:
Scans a local git repository for secrets that are being leaked deep within the
commit history.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Scans a local git repository for secrets within the commit history

License:        Unlicense
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/cmd/%{name} %{goipath}/cmd/%{name}

# No shell completion until this is fixed:
# https://github.com/owenrumney/squealer/issues/68

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/cmd/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
