# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/aquasecurity/tfsec
%global goipath         github.com/aquasecurity/tfsec
Version:                0.58.6

%gometa

%global common_description %{expand:
Security scanner for your Terraform code.}

%global golicenses      LICENSE
%global godocs          example CODE_OF_CONDUCT.md rules.md SIGNING.md\\\
                        CONTRIBUTING.md README.md examples

Name:           tfsec
Release:        1%{?dist}
Summary:        Security scanner for your Terraform code

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}
Patch0001:      0001-Remove-update-option-for-cli.patch

BuildRequires:  golang(github.com/apparentlymart/go-cidr/cidr)
BuildRequires:  golang(github.com/bmatcuk/doublestar)
BuildRequires:  golang(github.com/google/uuid)
BuildRequires:  golang(github.com/hashicorp/go-uuid)
BuildRequires:  golang(github.com/hashicorp/go-version)
BuildRequires:  golang(github.com/hashicorp/hcl/v2)
BuildRequires:  golang(github.com/hashicorp/hcl/v2/ext/tryfunc)
BuildRequires:  golang(github.com/hashicorp/hcl/v2/hclparse)
BuildRequires:  golang(github.com/hashicorp/hcl/v2/hclsyntax)
BuildRequires:  golang(github.com/liamg/clinch/prompt)
BuildRequires:  golang(github.com/liamg/clinch/terminal)
BuildRequires:  golang(github.com/liamg/gifwrap/pkg/ascii)
BuildRequires:  golang(github.com/liamg/tml)
BuildRequires:  golang(github.com/mitchellh/go-homedir)
BuildRequires:  golang(github.com/olekukonko/tablewriter)
BuildRequires:  golang(github.com/owenrumney/go-sarif/sarif)
BuildRequires:  golang(github.com/owenrumney/squealer/pkg/squealer)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/zclconf/go-cty-yaml)
BuildRequires:  golang(github.com/zclconf/go-cty/cty)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/convert)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/function)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/function/stdlib)
BuildRequires:  golang(github.com/zclconf/go-cty/cty/gocty)
BuildRequires:  golang(golang.org/x/crypto/bcrypt)
BuildRequires:  golang(golang.org/x/crypto/ssh)
BuildRequires:  golang(golang.org/x/text/encoding/ianaindex)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
%patch0001 -p1

%build
export LDFLAGS="-X github.com/aquasecurity/tfsec/version.Version=%{version}"

for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc example CODE_OF_CONDUCT.md rules.md SIGNING.md CONTRIBUTING.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Aug 17 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 0.58.6-1
- Initial package

