# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/aquasecurity/tfsec
%global goipath         github.com/aquasecurity/tfsec
Version:                1.26.3

%gometa

%global common_description %{expand:
Security scanner for your Terraform code.}

%global golicenses      LICENSE
%global godocs          docs _examples ARCHITECTURE.md CODE_OF_CONDUCT.md\\\
                        rules.md SIGNING.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Security scanner for your Terraform code

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
export LDFLAGS="-X github.com/aquasecurity/tfsec/version.Version=%{version}"
for cmd in cmd/tfsec ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs _examples ARCHITECTURE.md CODE_OF_CONDUCT.md rules.md SIGNING.md
%doc CONTRIBUTING.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
